# Generated by Django 4.2.10 on 2024-03-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='regularadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='regularuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupMembers',
        ),
        migrations.DeleteModel(
            name='RegularAdmin',
        ),
        migrations.DeleteModel(
            name='RegularUser',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role'),
        ),
    ]
