# Generated by Django 4.2.10 on 2024-03-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_remove_mygroup_permissions_remove_mygroup_users_role_and_more'),
        ('users', '0007_remove_user_roles_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roles.role'),
            preserve_default=False,
        ),
    ]
