# Generated by Django 4.2.10 on 2024-03-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_remove_mygroup_permissions_remove_mygroup_users_role_and_more'),
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='roles.mygroup'),
        ),
    ]
