# Generated by Django 4.2.10 on 2024-03-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='car_number',
        ),
    ]
