# Generated by Django 4.2.10 on 2024-03-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_access_level'),
        ('users', '0013_remove_user_car_number'),
    ]

    operations = [
    ]
