# Generated by Django 4.2.10 on 2024-03-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Название компании')),
                ('tax_identification_number', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('is_counterparty', models.BooleanField(default=False, verbose_name='Является контрагентом')),
                ('is_contractor', models.BooleanField(default=False, verbose_name='Является исполнителем')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('work_position', models.CharField(max_length=128, verbose_name='Должность')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.company', verbose_name='ID компании')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('number', models.CharField(max_length=256, unique=True, verbose_name='Номер договора')),
                ('contract_type', models.CharField(choices=[('С заказчиком', 'С заказчиком'), ('С контрагентом', 'С контрагентом')], max_length=256, verbose_name='Вид договора')),
                ('currency', models.CharField(choices=[('Руб', 'Руб'), ('Дол', 'Дол'), ('Евро', 'Евро')], max_length=32, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('На подписании', 'На подписании'), ('Подписан(оригинал)', 'Подписан(оригинал)'), ('Подписан(копия)', 'Подписан(копия)')], max_length=64, verbose_name='Статус')),
                ('status_date', models.DateField(verbose_name='Дата статуса')),
                ('sbt', models.BooleanField(verbose_name='Принят по Sbt')),
                ('contract_start_date', models.DateField(verbose_name='Дата начала договора')),
                ('contract_stop_date', models.DateField(verbose_name='Дата конца договора')),
                ('tracking', models.CharField(blank=True, max_length=32, verbose_name='Отслеживание')),
                ('printed_application_form', models.CharField(blank=True, max_length=64, verbose_name='Печатная форма заявки')),
                ('counterparty_agreement_form', models.BooleanField(verbose_name='Форма договора контрагента')),
                ('counterparty_application_form', models.BooleanField(verbose_name='Форма заявок контрагента')),
                ('additional_agreement', models.BooleanField(verbose_name='Есть дополнительное соглашение')),
                ('rates_set_by_contract', models.BooleanField(verbose_name='Ставки установлены договором')),
                ('contract_scan', models.FileField(blank=True, upload_to='contract_scan/%Y%m/', verbose_name='Скан договора')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='file_app.employee', verbose_name='Исполнитель')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='file_app.employee', verbose_name='Заказчик')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
