# Generated by Django 4.2.10 on 2024-03-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontract',
            name='sbt',
            field=models.BooleanField(default=False, verbose_name='Принят по Sbt'),
        ),
    ]
