# Generated by Django 4.2.10 on 2024-02-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('number', models.CharField(max_length=256)),
                ('customer', models.CharField(max_length=256)),
                ('contractor', models.CharField(max_length=256)),
                ('contract_type', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=64)),
                ('status_date', models.DateField()),
                ('sbt', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
    ]
