# Generated by Django 4.2.10 on 2024-03-17 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создавший пользователь'),
        ),
    ]
