# Generated by Django 4.2.10 on 2024-02-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_journal_delete_documentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.journaltype'),
        ),
    ]
