# Generated by Django 4.2.10 on 2024-03-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontract',
            name='additional_agreement',
            field=models.BooleanField(default=False, verbose_name='Есть дополнительное соглашение'),
        ),
        migrations.AlterField(
            model_name='documentcontract',
            name='counterparty_agreement_form',
            field=models.BooleanField(default=False, verbose_name='Форма договора контрагента'),
        ),
        migrations.AlterField(
            model_name='documentcontract',
            name='counterparty_application_form',
            field=models.BooleanField(default=False, verbose_name='Форма заявок контрагента'),
        ),
        migrations.AlterField(
            model_name='documentcontract',
            name='rates_set_by_contract',
            field=models.BooleanField(default=False, verbose_name='Ставки установлены договором'),
        ),
        migrations.AlterField(
            model_name='documentcontract',
            name='sbt',
            field=models.BooleanField(default=False, verbose_name='Принят по Sbt'),
        ),
    ]
