# Generated by Django 4.2.10 on 2024-02-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0003_journaltype_alter_journal_journal_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal',
            new_name='JournalContract',
        ),
        migrations.RenameModel(
            old_name='JournalType',
            new_name='JournalContractType',
        ),
    ]
