# Generated by Django 4.2.10 on 2024-02-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_rename_journal_journalcontract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalcontract',
            name='journal_type',
        ),
        migrations.DeleteModel(
            name='JournalContractType',
        ),
    ]
