# Generated by Django 4.2.10 on 2024-03-02 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_app', '0005_remove_journalcontract_journal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата договора')),
                ('number', models.CharField(max_length=256, unique=True, verbose_name='Номер договора')),
                ('customer', models.CharField(max_length=256, verbose_name='Заказчик')),
                ('contractor', models.CharField(max_length=256, verbose_name='Исполнитель')),
                ('contract_type', models.CharField(choices=[('С заказчиком', 'С заказчиком'), ('С контрагентом', 'С контрагентом')], max_length=256, verbose_name='Вид договора')),
                ('currency', models.CharField(choices=[('Руб', 'Руб'), ('Дол', 'Дол'), ('Евро', 'Евро')], max_length=32, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('На подписании', 'На подписании'), ('Подписан(оригинал)', 'Подписан(оригинал)'), ('Подписан(копия)', 'Подписан(копия)')], max_length=64, verbose_name='Статус')),
                ('status_date', models.DateField(verbose_name='Дата статуса')),
                ('sbt', models.BooleanField(verbose_name='Принят по Sbt')),
                ('contract_start_date', models.DateField(verbose_name='Дата начала договора')),
                ('contract_stop_date', models.DateField(verbose_name='Дата конца договора')),
                ('tracking', models.CharField(max_length=32, verbose_name='Отслеживание')),
                ('printed_application_form', models.CharField(max_length=64, verbose_name='Печатная форма заявки')),
                ('counterparty_agreement_form', models.BooleanField(verbose_name='Форма договора контрагента')),
                ('counterparty_application_form', models.BooleanField(verbose_name='Форма заявок контрагента')),
                ('additional_agreement', models.BooleanField(verbose_name='Есть дополнительное соглашение')),
                ('rates_set_by_contract', models.BooleanField(verbose_name='Ставки установлены договором')),
                ('contract_scan', models.FileField(upload_to='contract_scan/% Y_% m/', verbose_name='Скан договора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создавший пользователь')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='JournalContract',
        ),
    ]
