# Generated by Django 4.2.10 on 2024-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0007_alter_documentcontract_contract_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontract',
            name='printed_application_form',
            field=models.CharField(blank=True, max_length=64, verbose_name='Печатная форма заявки'),
        ),
        migrations.AlterField(
            model_name='documentcontract',
            name='tracking',
            field=models.CharField(blank=True, max_length=32, verbose_name='Отслеживание'),
        ),
    ]
