# Generated by Django 4.2.10 on 2024-03-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0008_alter_documentcontract_printed_application_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontract',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Примечание'),
        ),
    ]
