# Generated by Django 4.2.10 on 2024-03-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0009_documentcontract_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, unique=True, verbose_name='Название компании')),
                ('tax_identification_number', models.IntegerField(unique=True, verbose_name='ИНН')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, unique=True, verbose_name='Название компании')),
                ('tax_identification_number', models.IntegerField(unique=True, verbose_name='ИНН')),
                ('is_counterparty', models.BooleanField(default=False, verbose_name='Является контрагентом')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('work_position', models.CharField(max_length=128, verbose_name='Должность')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.customercompany', verbose_name='ID компании')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('work_position', models.CharField(max_length=128, verbose_name='Должность')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.contractorcompany', verbose_name='ID компании')),
            ],
        ),
        migrations.AlterField(
            model_name='documentcontract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.contractor', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='documentcontract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_app.customer', verbose_name='Заказчик'),
        ),
    ]
