# Generated by Django 4.2.10 on 2024-03-04 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0006_mygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='mygroup',
            name='users',
            field=models.ManyToManyField(related_name='my_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
