# Generated by Django 4.2.10 on 2024-03-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0007_mygroup_permissions_alter_mygroup_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygroup',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='mygroup',
            name='users',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.ManyToManyField(to='auth.permission')),
            ],
        ),
        migrations.AddField(
            model_name='employeeassessmentrecord',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roles.role'),
            preserve_default=False,
        ),
    ]
