# Generated by Django 4.2.10 on 2024-03-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_remove_mygroup_permissions_remove_mygroup_users_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeAssessmentRecord',
        ),
    ]
